### ISSUE TITLE
frida.PermissionDeniedError: unable to access process with pid 3048 from the current user account

### ISSUE THREAD

**Issue by mi1wei** [f4l1k/WeChatOpenDevTools-Python-arm#2]
Traceback (most recent call last):
  File "/Users/miwei/PycharmProjects/WeChatOpenDevTools-Python-arm-main/main.py", line 18, in <module>
    main()
  File "/Users/miwei/PycharmProjects/WeChatOpenDevTools-Python-arm-main/main.py", line 13, in main
    commons.load_wechatEx_configs()
  File "/Users/miwei/PycharmProjects/WeChatOpenDevTools-Python-arm-main/utils/commons.py", line 39, in load_wechatEx_configs
    self.inject_wehcatEx(pid, wehcatEx_hookcode)
  File "/Users/miwei/PycharmProjects/WeChatOpenDevTools-Python-arm-main/utils/commons.py", line 24, in inject_wehcatEx
    session = frida.attach(pid)
  File "/Users/miwei/PycharmProjects/WeChatOpenDevTools-Python-arm-main/venv/lib/python3.9/site-packages/frida/__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
  File "/Users/miwei/PycharmProjects/WeChatOpenDevTools-Python-arm-main/venv/lib/python3.9/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/Users/miwei/PycharmProjects/WeChatOpenDevTools-Python-arm-main/venv/lib/python3.9/site-packages/frida/core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
frida.PermissionDeniedError: unable to access process with pid 3048 from the current user account

**Comment by f4l1k** [comment]
权限原因造成，mac需要关闭sip

**Comment by sunxihe** [comment]
没有打开sip  也报这个错误
