### ISSUE TITLE
虚拟环境运行不了吗

### ISSUE THREAD

**Issue by wqy8593521** [f4l1k/WeChatOpenDevTools-Python-arm#6]
sudo python main.py 
Password:
\ \        /\ \  /    __ \           __ __|           |      
 \ \  \   /  \  /     |   |  _ \\ \   / |  _ \   _ \  |  __| 
  \ \  \ /      \     |   |  __/ \ \ /  | (   | (   | |\__ \ 
   \_/\_/    _/\_\   ____/ \___|  \_/  _|\___/ \___/ _|____/ 
                                                             
Traceback (most recent call last):
  File "/Users/wangqiyan/PycharmProjects/WeChatOpenDevTools-Python-arm/main.py", line 32, in <module>
    main()
  File "/Users/wangqiyan/PycharmProjects/WeChatOpenDevTools-Python-arm/main.py", line 26, in main
    commons.load_wechatEx_configs()
  File "/Users/wangqiyan/PycharmProjects/WeChatOpenDevTools-Python-arm/utils/commons.py", line 39, in load_wechatEx_configs
    self.inject_wehcatEx(pid, wehcatEx_hookcode)
  File "/Users/wangqiyan/PycharmProjects/WeChatOpenDevTools-Python-arm/utils/commons.py", line 24, in inject_wehcatEx
    session = frida.attach(pid)
  File "/Users/wangqiyan/anaconda3/envs/WeChatOpenDevTools-Python-arm/lib/python3.9/site-packages/frida/__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
  File "/Users/wangqiyan/anaconda3/envs/WeChatOpenDevTools-Python-arm/lib/python3.9/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/Users/wangqiyan/anaconda3/envs/WeChatOpenDevTools-Python-arm/lib/python3.9/site-packages/frida/core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
frida.PermissionDeniedError: unable to access process with pid 38498 from the current user account

**Comment by f4l1k** [comment]
禁用系统完整性保护
